config/routes.rb
ScoreEngine::Application.routes.draw do
  # Root
  root :to => 'page#home'

  # Users
  devise_for :users

  # Teams
  resources :teams
  get '/teams/:id/graph' => 'teams#graph', as: :team_graph

  # Client Updates
  get '/client_update/poll' => 'client_update#poll'

  # Services
  post '/services/:id/clear' => 'services#clear', as: :clear_service
  post '/logs/:id/clear/:log_id' => 'services#clear', as: :clear_service_log
  get '/services/:id/status/:last_log_id' => 'services#status'
  post '/services/:id/power' => 'services#power', as: :service_power
  get '/services/:id/graph/:type' => 'services#graph', as: :services_graph
  resources :services

  # Scoreboard
  get '/scoreboard' => 'scoreboard#index', as: :scoreboard
  get '/scoreboard/graph/:graph_model/:id/:graph_name' => 'scoreboard#graph'

  # Users
  get '/users' => 'users#index', as: :users
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update', as: :user

  # Team Messages
  resources :team_messages, path: 'messages'
  get '/messages/new/:reply_id' => 'team_messages#new', as: :team_messages_reply
  get '/messages/:id/download' => 'team_messages#download', as: :team_message_download

  # Server Manager
  get '/serverManager' => 'server_manager#index', as: :server_manager
  post '/serverManager/refresh' => 'server_manager#refresh', as: :server_manager_refresh
  post '/serverManager/start_libvirt' => 'server_manager#start_libvirt', as: :server_manager_start_libvirt
  get '/serverManager/:id/:command' => 'server_manager#command', as: :server_manager_command
  post '/serverManager/:id/:command' => 'server_manager#command'

  # Tools
  get 'tools/hash' => 'tools#hash', as: :hash_tool
  post 'tools/hash' => 'tools#hash_post'
  get 'tools/dns' => 'tools#dns', as: :dns_tool
  post 'tools/dns' => 'tools#dns_post'
  get 'tools/daemon_log' => 'tools#daemon_log', as: :daemon_log
end

app/models/service.rb
class Service < ActiveRecord::Base
  #attr_accessible :name, :params, :worker, :team_id, :on, :public

  validates_presence_of :name, :worker, :team_id
  validates_inclusion_of :worker, in: Workers::GenericWorker::WORKERS.keys.collect{|k| k.to_s}

  serialize :params, Hash

  has_many :service_logs
  belongs_to :team

  def last_status
    log = self.service_logs.select(:status).order('created_at desc').first
    return ServiceLog::STATUS_OFF if log.nil?
    log.status
  end

  def status
    on ? last_status : ServiceLog::STATUS_OFF
  end

  def worker_class
    klass = "Workers::#{Workers::GenericWorker::WORKERS[worker]}".constantize
    raise "Invalid Worker Specified" unless klass <= Workers::GenericWorker
    klass
  end

  def team_name
    team_id.nil? ? 'None' : team.name
  end

  def up_time
    @up_time ||= nil
    if @up_time.nil?
      log_count = service_logs.count
      success_count = service_logs.where(status: ServiceLog::STATUS_RUNNING).count
      @up_time = log_count > 0 ? ((success_count.to_f / log_count.to_f) * 100.0).to_i : 0
    end
    @up_time
  end

  def make_worker
    worker_class.new(self, {dns_server: (team.nil? ? nil : team.dns_server), domain: (team.nil? ? nil : team.domain)})
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_admin!, except: [:index, :show, :status, :daemon_status, :graph]
  before_filter :authenticate_not_red_team!, only: [:show]
  before_filter do
    @header_icon = 'dashboard'
  end

  # GET /services
  def index
    @services = Hash.new([])
    teams_query = Team.includes(:services).order('teams.id')
    teams_query = teams_query.where(id: current_user.team_id) if (not current_user.team_id.nil?) and current_user.team_id > 0
    teams_query = teams_query.where('services.public' => true) unless current_user.is_admin
    @teams = teams_query.all
    @teams.each {|t| @services[t] += t.services}

    # Construct overview
    @overview = {}
    if current_user.is_admin or current_user.is_red_team
      @services.each do |team,service_list|
        service_list.each do |service|
          unless @overview.key? service.name
            @overview[service.name] = {}
          end
          @overview[service.name][team.id] = {service_id: service.id, service_img: service_img(service)}
        end
      end
    end

    @header_text = 'Services'
  end

  # GET /services/1
  def show
    @service = Service.find(params[:id])

    # Redirect if user should not be accessing this service
    unless current_user_admin?
      if @service.team_id.blank? or @service.team_id != current_user.team_id or (! @service.public? and ! current_user_admin?)
        redirect_to services_path, flash: {error: 'You do not have sufficient privleges for that'}
      end
    end

    @header_text = @service.name
    if @service.public
      private_tag = ''
    else
      private_tag = '<div class="label secondary">private</a>'.html_safe
    end
    @header_text = "Team #{@service.team_name} - #{@header_text} #{private_tag}".html_safe if current_user_admin?
    @header_class = service_class @service

    # Build services the user can view for this team
    @service_list = Service.where(team_id: @service.team_id)
    @service_list = @service_list.where(public: true) unless current_user_admin?
    @service_list = @service_list.all
  end

  # GET /services/new
  def new
    @header_text = 'New Service'
    @service = Service.new

    if params.include? :worker_name
      render partial: 'worker_form', locals: {worker_name: params[:worker_name]}
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
    @header_text = 'Edit Service'

    if params.include? :worker_name
      render partial: 'worker_form', locals: {worker_name: params[:worker_name]}
    end
  end

  # POST /services
  def create
    @header_text = 'New Service'
    @service = nil
    service_params = params[:service]

    begin
      if service_params[:team_id] == 'all'
        Team.select(:id).all.each do |team|
          service_params[:team_id] = team.id
          @service = Service.new(service_params)
          raise unless @service.save
        end
        redirect_to services_url, notice: 'Service was successfully created for all teams.'
      else
        @service = Service.new(service_params)
        raise unless @service.save
        redirect_to @service, notice: 'Service was successfully created.'
      end
    #rescue
    #  render action: 'new'
    end
  end

  # PUT /services/1
  def update
    @service = Service.find(params[:id])
    @header_text =' "Edit Service"'

    if @service.update_attributes(params[:service])
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /services/1
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    redirect_to services_url
  end

  # POST /services/:id/clear/[:log_id]
  def clear
    if params[:log_id].nil?
      service = Service.find(params[:id])
      if service.service_logs.destroy_all
        flash[:notice] = "Cleared logs for '#{service.name}'"
      end
      redirect_to service
    else
      log = ServiceLog.find(params[:log_id])
      service = log.service
      log_id = log.id
      if log.destroy
        flash[:notice] = "Cleared log ##{log_id} for '#{service.name}'"
      end
      redirect_to service
    end
  end

  # POST /services/:id/power
  def power
    service = Service.find(params[:id])

    service.on = ! service.on
    service.save

    redirect_to service
  end

  def graph
    raise 'Invalid Access' if current_user.is_red_team

    data = []
    if params[:team_id] == 'overview'
      Team.all.each do |team|
        data << {name: "Team #{team.name}", data: ServiceLog.running_percentage(team.services.select(:id).map(&:id))}
      end
    else
      team = Team.where(id: params[:team_id]).first
      unless team.nil?
        team.services.select([:id, :name]).all.each do |service|
          data << {name: service.name, data: ServiceLog.running_percentage(service.id)}
        end
      end
    end

    #rand = Random.new
    #render json: [{name: 'Google', data: {10.minutes.ago=>rand.rand, 5.minutes.ago=>rand.rand, 0.minutes.ago=>rand.rand}}, {name: 'Google DNS', data: {10.minutes.ago => rand.rand, 5.minutes.ago => rand.rand, 0.minutes.ago => rand.rand}}]
    render json: data
  end
end

app/views/services/_form.html.haml
.row
  = form_for @service do |f|
    = f.hidden_field :id

    %fieldset
      %legend Basic
      = render partial: 'layouts/form_row', locals: {f: f, model: @service, html_form: f.text_field(:name), row_id: :name, row_name: 'Name', small_size: 12, large_size: 6, hint: 'Name of Service', required: true}
      = render partial: 'layouts/form_row', locals: {f: f, model: @service, html_form: f.select(:worker, Workers::GenericWorker::WORKERS.collect{|name,_| [name,name]}), row_id: :worker, row_name: 'Worker', small_size: 6, large_size:3, hint: 'Worker Class', required: true}
      = render partial: 'layouts/form_row', locals: {f: f, model: @service, html_form: f.select(:team_id, Team.options_list.select{|t| t[1] != 'all' or @service.team_id.nil?}), row_id: :team_id, row_name: 'Team', small_size:6, large_size: 3, hint: 'Assign this service to a team', required: true}
      .row
      = render partial: 'layouts/form_row_slider', locals: {f: f, model: @service, row_id: :public, row_name: 'Public?'}
      = render partial: 'layouts/form_row_slider', locals: {f: f, model: @service, row_id: :on, row_name: 'On?'}

    %fieldset
      %legend Parameters
      %div#service-params
        = render partial: 'worker_form', locals: {worker_name: (@service.worker || Workers::GenericWorker::WORKERS.keys.first)}

    .small-12.columns.left
      = f.submit ((%w{new create}.include? params[:action]) ? 'Create' : 'Edit'), class: 'button'

app/views/services/_service_log.html.haml
.row.service-log
  .small-2.columns
    %img{src: service_log_img(log)}
  .small-10.columns
    %p
      %strong Service Check:
      = log.message
    %ul.inline-list
      - if current_user_admin?
        %li
          = link_to 'Debug', '#', onclick: 'toggleLogDebug(this)'
      - if current_user_admin?
        %li
          = link_to 'Remove', clear_service_log_path(log.service_id,log.id), method: :post
      %li.time
        = log.created_at.strftime '%I:%M:%S %p'

    - if current_user_admin?
      .row.debug
        .small-10.columns.panel
          %p
            %strong Debug:
            = simple_format h(log.debug_message)
  %hr

app/views/services/_worker_form.html.haml
- klass = "Workers::#{Workers::GenericWorker::WORKERS[worker_name]}".constantize
- unless klass <= Workers::GenericWorker
  - raise 'Invalid Worker Specified'
%div{id: "params-#{worker_name}"}
  - klass.service_params.each do |key, param|
    - value = @service.params[worker_name]
    - if value.nil?
      - value = param[:default]
    - else
      - value = value[key.to_s] || param[:default]
    = render partial: 'layouts/form_row', locals: {f: nil, model: nil, html_form: text_field_tag("service[params][#{worker_name}][#{key.to_s}]", value.to_s), row_id: nil, row_name: param[:name], small_size: 12, large_size: 6, hint: (param[:description] || '&nbsp;'), required: param[:required]}

app/views/services/edit.html.haml
= render 'form'

app/views/services/index.html.haml
- if @services.length < 1
  .twelve.panel
    %b There are no services

- else
  %dl.tabs{'data-tab'=>''}
    - is_first = true
    - if (current_user.is_admin or current_user.is_red_team) and @services.length > 1
      %dd.active{id: 'overview'}
        = link_to "Overview", "#overviewTab"
        - is_first = false
    - @services.each do |team, service_list|
      - team = Team.new(name: 'None', id: 0) if team.nil?
      %dd{class: (is_first ? 'active':''), id: team.id}
        = link_to "Team #{team.name}", "#team#{team.id}Tab"
      - is_first = false

  .tabs-content#team-tabs
    - is_first = true
    - if (current_user.is_admin or current_user.is_red_team) and @services.length > 1
      #overviewTab.content.active

        - unless current_user.is_red_team
          .small-1.end
            = link_to_function fa_icon('bar-chart-o'), "loadGraph('graphSectionOverview')", class:'button expandGraph round'
          .graphSection.panel.small-12.columns.hidden{id: 'graphSectionOverview'}
            .graphArea{id: "serviceGraphOverview", 'data-graph-url' => services_graph_path('overview')}
              Loading...

        %table.service-overview
          %thead
            %tr
              %th.two Service
              - @teams.each do |team|
                %th.two= "Team #{team.name}"
          %tbody
            - @overview.each do |service_name, overview_data|
              %tr
                %td
                  %b= service_name
                - @teams.each do |team|
                  %td
                    - if overview_data.key? team.id
                      %a{href: service_path(overview_data[team.id][:service_id])}
                        %img{src:overview_data[team.id][:service_img], id: "overviewIcon#{overview_data[team.id][:service_id]}"}
      - is_first = false
    - @services.each do |team, service_list|
      - team = Team.new(name: 'None', id: 0) if team.nil?
      .content{id: "team#{team.id}Tab", class: (is_first ? 'active':'')}
        = hidden_field_tag 'team-id', team.id

        - unless current_user.is_red_team
          .progress.success.text.small-11.columns{id: "uptime#{team.id}"}
            .meter{style:"width:#{team.uptime}%"}
              .text
                = "#{team.uptime}%"
          .small-1.columns
            = link_to_function fa_icon('bar-chart-o'), "loadGraph('graphSection#{team.id}')", class:'button expandGraph round'
          .graphSection.panel.small-12.columns.hidden{id: "graphSection#{team.id}"}
            .graphArea{id: "serviceGraph#{team.id}", 'data-graph-url' => services_graph_path(team.id)}
              Loading...

        %table.small-12.columns.services
          %thead
            %tr
              %th
              %th Name
              %th Worker
              %th Host
              %th Uptime
              - if current_user_admin?
                %th

          %tbody
            - service_list.each do |service|

              - unless service.blank?
                %tr{class: service_class(service), id:"service#{service.id}"}
                  %td.service_img{style:'padding:0px;'}
                  %td
                    = link_to service.name, service
                    - unless service.public
                      .label.secondary private
                  %td= service.worker
                  %td= service.params[service.worker]['rhost']+" : "+service.params[service.worker]['rport']
                  %td= "#{service.up_time}%"
                  - if current_user_admin?
                    %td
                      %ul.inline-list
                        %li= link_to fa_icon(:pencil, text: 'Edit'), edit_service_path(service)
                        %li= link_to fa_icon('trash-o', text: 'Destroy'), service, method: :delete, data: { confirm: 'Are you sure?' }
      - is_first = false

- if current_user_admin?
  - if @services.length > 0
    %br
  = link_to fa_icon(:cloud, text: 'Add Service'), new_service_path, class: 'button'
  = link_to fa_icon(:group, text: 'Add Team'), new_team_path, class: 'button'
  - if @services.length > 0
    = link_to_function fa_icon(:pencil, text: 'Edit Team'), 'editTeamLink()', class: 'button'

:javascript
  function editTeamLink() {
    var team_id = $('#team-tabs .active #team-id').val();
    if(!team_id)
      alert('Not a valid team');
    else
      document.location = '/teams/' + team_id + "/edit"
  }

app/views/services/show.html.haml
= hidden_field_tag 'service_id', @service.id
- last_log = @service.service_logs.order('created_at desc').first
- last_log_id = last_log.nil? ? 0 : last_log.id
= hidden_field_tag 'last_log_id', last_log_id

.row
  .small-3.columns
    .panel.services
      %h3= link_to "Team #{@service.team_name}", services_path+"#team#{@service.team_id}"
      %br
      - @service_list.each do |s|
        .row
          = link_to s.name, s, class: 'button small-12 columns '+service_class(s), id: "service#{s.id}"

  .small-9.columns
    .row
      .small-12.columns
        .row
          .small-2.columns{style:'text-align: right;'}
            %h5 Uptime:
          .small-10.columns
            .progress.success.text#uptime
              .meter{style:"width:#{@service.up_time}%"}
                .text
                  = "#{@service.up_time}%"
    - if current_user_admin?
      .row
        %ul.button-group.even
          %li= link_to fa_icon(:pencil, text: 'Edit'), edit_service_path(@service), class:'button'
          - if @service.on
            %li= link_to fa_icon('power-off', text: 'Off'), service_power_path(@service), method: :post, class: 'button alert', confirm: 'Are you sure you want to POWER OF this service?'
          - else
            %li= link_to fa_icon('power-off', text: 'On'), service_power_path(@service), method: :post, class: 'button success', confirm: 'Are you sure you want to POWER ON this service?'
          %li= link_to fa_icon('trash-o', text: 'Clear'), clear_service_path(@service), method: :post, class: 'button alert', confirm: 'Are you sure you want to CLEAR LOGS for this service?'

    - if @service.service_logs.count == 0
      .row
        .small-10.columns.small-offset-2
          %h3 No Logs

    - @service.service_logs.order('created_at desc').each do |log|
      #service_logs
        = render partial: 'service_log', locals: {log: log}