config/routes.rb
ScoreEngine::Application.routes.draw do
  # Root
  root :to => 'page#home'

  # Users
  devise_for :users

  # Teams
  resources :teams
  get '/teams/:id/graph' => 'teams#graph', as: :team_graph

  # Client Updates
  get '/client_update/poll' => 'client_update#poll'

  # Services
  post '/services/:id/clear' => 'services#clear', as: :clear_service
  post '/logs/:id/clear/:log_id' => 'services#clear', as: :clear_service_log
  get '/services/:id/status/:last_log_id' => 'services#status'
  post '/services/:id/power' => 'services#power', as: :service_power
  get '/services/:id/graph/:type' => 'services#graph', as: :services_graph
  resources :services

  # Scoreboard
  get '/scoreboard' => 'scoreboard#index', as: :scoreboard
  get '/scoreboard/graph/:graph_model/:id/:graph_name' => 'scoreboard#graph'

  # Users
  get '/users' => 'users#index', as: :users
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update', as: :user

  # Team Messages
  resources :team_messages, path: 'messages'
  get '/messages/new/:reply_id' => 'team_messages#new', as: :team_messages_reply
  get '/messages/:id/download' => 'team_messages#download', as: :team_message_download

  # Server Manager
  get '/serverManager' => 'server_manager#index', as: :server_manager
  post '/serverManager/refresh' => 'server_manager#refresh', as: :server_manager_refresh
  post '/serverManager/start_libvirt' => 'server_manager#start_libvirt', as: :server_manager_start_libvirt
  get '/serverManager/:id/:command' => 'server_manager#command', as: :server_manager_command
  post '/serverManager/:id/:command' => 'server_manager#command'

  # Tools
  get 'tools/hash' => 'tools#hash', as: :hash_tool
  post 'tools/hash' => 'tools#hash_post'
  get 'tools/dns' => 'tools#dns', as: :dns_tool
  post 'tools/dns' => 'tools#dns_post'
  get 'tools/daemon_log' => 'tools#daemon_log', as: :daemon_log
end

app/controllers/server_manager_controller.rb
class ServerManagerController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_admin!
  before_filter except: :start_libvirt do
    @header_text = 'Server Manager'
    @header_icon = 'desktop'

    begin
      unless Settings.server_manager.nil?
        if !Settings.server_manager.aws.nil? and Settings.server_manager.aws.enable
          @server_manager = ServerManager::AWSManager.get_instance
        elsif !Settings.server_manager.libvirt.nil? and Settings.server_manager.libvirt.enable
          @server_manager = ServerManager::LibvirtManager.get_instance
        end
      end
      if @server_manager.nil?
        @server_manager_error = 'No Server Manager Enabled'
        render 'error'
      else
        if @server_manager.server_list.length <= 0
          @server_manager_error = 'No Servers in Manager'
          render 'error'
        end
      end
    rescue Libvirt::ConnectionError => e
      @server_manager_error = e.to_s
      if e.to_s.include? 'virConnectOpen failed: unable to connect to server'
        @server_manager_error += "<br/><br/>Start libvirtd with:<br/><pre>$ libvirtd -ldf /etc/libvirt/libvirtd.conf</pre><br/>#{view_context.link_to 'Start Libvirtd', server_manager_start_libvirt_path, class: 'button', method: :post}"
      end
      render 'error'
    end
  end

  after_filter do
    @server_manager.close unless @server_manager.nil?
  end

  # GET /server_manager
  def index
    @header_text = "#{@header_text} #{view_context.link_to((@server_manager.is_fresh ? 'fresh' : 'old'), server_manager_refresh_path, method: :post, class: "label #{@server_manager.is_fresh ? 'alert' : 'secondary'}")}".html_safe
  end

  # GET/POST /server_manager/:id/:command
  def command
    if @server_manager.available_commands.include? params[:command].to_sym
      if request.post? || params[:command] == 'screenshot'
        data = nil
        args = [params[:command], params[:id]]
        args << params[:data] if params[:data]
        #begin
          data = @server_manager.try(*args)
        #rescue Exception => e
          #flash[:error] = e.to_s
        #end
        if params[:command] == 'screenshot'
          send_data open(data[0], 'rb').read, type: data[1]
        else
          redirect_to server_manager_path
        end
      else
        @server = @server_manager.get_server params[:id]
        render action: params[:command], layout: nil
      end
    else
      flash[:error] = 'Error: Command not available: '+params[:command]
      redirect_to server_manager_path
    end
  end

  # POST /server_manager/refresh
  def refresh
    @server_manager.clear_cache
    redirect_to server_manager_path
  end

  # POST /server_manager/start_libvirt
  def start_libvirt
    system('libvirtd -ldf /etc/libvirt/libvirtd.conf')
    redirect_to server_manager_path
  end
end

app/views/server_manager/_aws_instance.html.haml
%ul{style:'margin-left: 10px'}
  %li= "Last Launch: #{time_ago_in_words(s[:last_launch])} ago" unless s[:last_launch].nil?
  %li= "Private IP: #{s[:private_ip]}"
  %li= "Public IP: #{s[:public_ip]}"

app/views/server_manager/_libvirt_instance.html.haml
%ul{style:'margin-left: 10px'}
  - if s[:snapshots].length > 0
    %li= "#{pluralize s[:snapshots].length, 'Snapshot'} available"
  - else
    %li No snapshots
  - if s[:rdp_port]
    %li= "RDP on port #{s[:rdp_port]}"
  - else
    %li No RDP

app/views/server_manager/error.html.haml
%h3= @server_manager_error.html_safe

app/views/server_manager/index.html.haml
.small-12.columns#server_blocks
  - i = 0
  - @server_manager.server_list.sort_by{|s| s[:name]}.sort_by{|s| s[:status] == :running ? 0 : (s[:status] == :paused ? 1 : 2)}.each do |s|
    .small-5.columns.panel{class: "#{s[:status].to_s}"}
      %h4
        -if s[:platform] == :linux
          = fa_icon :linux
        -elsif s[:platform] == :windows
          = fa_icon :windows
        - else
          = fa_icon 'hdd-o'
        = s[:name]
        = link_to_function fa_icon('camera'), "screenshotOpen('#{s[:id]}')", class: "button round screen-button", style: "#{(s[:status] != :running or !@server_manager.available_commands.include?(:screenshot)) ? 'display:none !important;' : ''}"
      = render partial: "#{s[:manager]}_instance", locals: {s: s}
      %a{href:'#', class: 'button split command'}
        %span{'data-dropdown'=>"commands#{i}"}
      %ul.f-dropdown{'data-dropdown-content'=>'', id: "commands#{i}"}
        - if @server_manager.available_commands.include? :pause
          - if s[:status] == :paused
            %li= link_to fa_icon('play', text: 'Resume'), server_manager_command_path(s[:id], :resume), method: :post
          - elsif s[:status] == :running
            %li= link_to fa_icon('pause', text: 'Pause'), server_manager_command_path(s[:id], :pause), method: :post
        - if @server_manager.available_commands.include? :reboot and s[:status] == :running
          %li= link_to fa_icon('retweet', text: 'Reboot'), server_manager_command_path(s[:id], :reboot), method: :post
        - if @server_manager.available_commands.include? :power_off
          - if s[:status] == :running
            %li= link_to fa_icon('power-off', text: 'Power Off'), server_manager_command_path(s[:id], :power_off), method: :post
          - elsif s[:status] == :down
            %li= link_to fa_icon('power-off', text: 'Power On'), server_manager_command_path(s[:id], :power_on), method: :post
        - if @server_manager.available_commands.include? :rename and s[:status] == :down
          %li= link_to fa_icon('pencil', text: 'Rename'), server_manager_command_path(s[:id], :rename), 'data-reveal-id' => 'ajax_modal', 'data-reveal-ajax' => 'true'
        - if @server_manager.available_commands.include? :revert and s[:status] == :down and s[:snapshots].length > 0
          %li= link_to fa_icon('frown-o', text: 'Revert to Snapshot'), server_manager_command_path(s[:id], :revert), 'data-reveal-id' => 'ajax_modal', 'data-reveal-ajax' => 'true'
        - if @server_manager.available_commands.include? :snapshot and s[:status] == :down
          %li= link_to fa_icon('thumb-tack', text: 'New Snapshot'), server_manager_command_path(s[:id], :snapshot), 'data-reveal-id' => 'ajax_modal', 'data-reveal-ajax' => 'true'
    - if i.odd?
      .small-2
        &nbsp;
    - i += 1

#ajax_modal.reveal-modal.tiny(data-reveal)
#screen_modal.reveal-modal.tiny(data-reveal)
  %a.close-reveal-modal &#215;
  = image_tag '', id: 'screen_img'

:javascript
  var screenInterval = null;
  function screenshotOpen(server_id) {
    $('#screen_modal #screen_img').attr('src', '#{server_manager_command_path('@id','screenshot')}?'.replace('@id',server_id) + new Date().getTime());
    $('#screen_modal').foundation('reveal', 'open');
  }
  function updateScreenShot() {
    var src = $('#screen_modal #screen_img').attr('src');
    src = src.split('?')[0] + '?' + new Date().getTime();
    $('#screen_modal #screen_img').attr('src', src);
  }
  $(document).on('opened', '#screen_modal', function() {
    if(screenInterval != null)
      clearInterval(screenInterval);
    screenInterval = setInterval(updateScreenShot, 3000);
  });
  $(document).on('closed', '#screen_modal', function() {
    screenInterval = clearInterval(screenInterval);
    screenInterval = null;
  });

app/views/server_manager/rename.html.haml
%a.close-reveal-modal &#215;
%h3 Rename Server
= form_tag server_manager_command_path(@server[:id], 'rename') do
  .row
    .columns.hint.small-8
      %label
      = text_field_tag 'data', @server[:name]
      %small.hint Rename the server
  .row
    .columns.hint.small-4
      = submit_tag 'Go', class: 'button'

app/views/server_manager/revert.html.haml
%a.close-reveal-modal &#215;
%h3 Revert to Snapshot
= form_tag server_manager_command_path(@server[:id], :revert) do
  .row
    .columns.hint.small-8
      %label
      = select_tag 'data', options_for_select([['Choose Snapshot', nil]].concat(@server[:snapshots]), nil)
      %small.hint Reset server to snapshot
  .row
    .columns.hint.small-4
      = submit_tag 'Go', class: 'button'

app/views/server_manager/snapshot.html.haml
%a.close-reveal-modal &#215;
%h3 Create a Snapshot
= form_tag server_manager_command_path(@server[:id], :snapshot) do
  .row
    .columns.hint.small-8
      %label
      = text_field_tag 'data', '', placeholder: 'Snapshot Name'
      %small.hint
  .row
    .columns.hint.small-4
      = submit_tag 'Go', class: 'button'