config/routes.rb
ScoreEngine::Application.routes.draw do
  # Root
  root :to => 'page#home'

  # Users
  devise_for :users

  # Teams
  resources :teams
  get '/teams/:id/graph' => 'teams#graph', as: :team_graph

  # Client Updates
  get '/client_update/poll' => 'client_update#poll'

  # Services
  post '/services/:id/clear' => 'services#clear', as: :clear_service
  post '/logs/:id/clear/:log_id' => 'services#clear', as: :clear_service_log
  get '/services/:id/status/:last_log_id' => 'services#status'
  post '/services/:id/power' => 'services#power', as: :service_power
  get '/services/:id/graph/:type' => 'services#graph', as: :services_graph
  resources :services

  # Scoreboard
  get '/scoreboard' => 'scoreboard#index', as: :scoreboard
  get '/scoreboard/graph/:graph_model/:id/:graph_name' => 'scoreboard#graph'

  # Users
  get '/users' => 'users#index', as: :users
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update', as: :user

  # Team Messages
  resources :team_messages, path: 'messages'
  get '/messages/new/:reply_id' => 'team_messages#new', as: :team_messages_reply
  get '/messages/:id/download' => 'team_messages#download', as: :team_message_download

  # Server Manager
  get '/serverManager' => 'server_manager#index', as: :server_manager
  post '/serverManager/refresh' => 'server_manager#refresh', as: :server_manager_refresh
  post '/serverManager/start_libvirt' => 'server_manager#start_libvirt', as: :server_manager_start_libvirt
  get '/serverManager/:id/:command' => 'server_manager#command', as: :server_manager_command
  post '/serverManager/:id/:command' => 'server_manager#command'

  # Tools
  get 'tools/hash' => 'tools#hash', as: :hash_tool
  post 'tools/hash' => 'tools#hash_post'
  get 'tools/dns' => 'tools#dns', as: :dns_tool
  post 'tools/dns' => 'tools#dns_post'
  get 'tools/daemon_log' => 'tools#daemon_log', as: :daemon_log
end

app/models/team_message.rb
class TeamMessage < ActiveRecord::Base
  #attr_accessible :content, :subject, :team_id, :file
  belongs_to :team

  def self.inbox_outbox options={}, &block
    options[:is_admin] ||= false

    team_messages = TeamMessage
    team_messages = team_messages.where(team_id: options[:team_id]) unless options[:team_id].nil? or options[:is_admin]
    team_messages = team_messages.where('id > ?', options[:last_message_id]) unless options[:last_message_id].nil?
    team_messages = block.call team_messages unless block.nil?
    team_messages = team_messages.order(created_at: :desc).all

    # Sort messages into inbox & outbox
    inbox = []
    outbox = []
    team_messages.each do |m|
      if m.from_admin? ^ options[:is_admin]
        inbox << m
      else
        outbox << m
      end
    end

    {inbox: inbox, outbox: outbox}
  end

  def self.user_new_messages user, last_time_checked
    return 0 if user.is_red_team
    messages = TeamMessage
    messages = messages.where(team_id: user.team_id) unless user.is_admin
    messages = messages.where('created_at > ?', last_time_checked)
    messages = messages.where(from_admin: !(user.is_admin))
    return messages.count
  end
end

app/controllers/team_messages_controller.rb
class TeamMessagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_not_red_team!
  before_filter :authenticate_admin!, only: [:destroy]
  before_filter do
    @header_icon = 'envelope'
  end

  UPLOAD_PATH = File.join(Rails.root, 'tmp', 'uploads')

  # GET /team_messages
  def index
    @header_text = 'Messages'

    @last_time_checked = last_time_inbox_checked
    last_time_inbox_checked Time.now

    messages = TeamMessage.inbox_outbox team_id: current_user.team_id, is_admin: current_user_admin?, last_message_id: params[:id] do |query|
      query = query.where('subject LIKE ?', "%#{params[:search]}%") unless params[:search].blank?
      query.order(:created_at).reverse_order
    end

    @inbox = messages[:inbox]
    @outbox = messages[:outbox]
  end

  # GET /team_messages/1
  def show
    @header_text = 'Message'
    @team_message = TeamMessage.find(params[:id])

    #@file_path = nil
    @file_name = nil
    if @team_message.file? and (not @team_message.file.blank?)
      #@file_path = File.join(UPLOAD_PATH, @team_message.file)
      @file_name = @team_message.file[@team_message.file.index('.')+1..-1]
    end
  end

  # GET /team_messages/new
  def new
    @header_text = 'New Message'
    @team_message = TeamMessage.new
    if params[:reply_id]
      @reply_message = TeamMessage.find(params[:reply_id])
      @team_message.team_id = @reply_message.team_id if current_user.is_admin
      @team_message.subject = "RE: #{@reply_message.subject}"
      @team_message.content = "\n\n=====================================================\nSent at: #{@reply_message.created_at}\nOriginal Message:\n#{@reply_message.content}"
    end
  end

  # POST /team_messages
  def create
    @team_message = nil
    message_params = params[:team_message]
    message_params['file'] = ''
    unless message_params[:file_upload].nil?
      data = message_params[:file_upload].read
      hash = Digest::MD5.hexdigest data
      filename = hash+'.'+message_params[:file_upload].original_filename
      FileUtils::mkdir_p(UPLOAD_PATH) unless File.exists?(UPLOAD_PATH)
      File.open(File.join(UPLOAD_PATH, filename), 'wb') do |file|
        file.write(data)
      end
      message_params['file'] = filename
    end
    message_params.delete :file_upload

    begin
      if message_params[:team_id] == 'all' and current_user.is_admin
        Team.select(:id).all.each do |team|
          message_params[:team_id] = team.id
          _send message_params
        end
      else
        _send message_params
      end
    rescue => e
      raise e
      @team_message.file = message_params['file']
      render action: 'new'
    end

    if message_params[:team_id] == 'all' and current_user.is_admin
      redirect_to team_messages_path, notice: 'Message was successfully sent to all teams'
    else
      redirect_to @team_message, notice: 'Message was successfully sent'
    end
  end

  # GET /team_messages/1/edit
  def edit
    @team_message = TeamMessage.find(params[:id])
    @header_text = 'Edit Message'
  end

  # PUT /team_messages/1
  def update
    @team_message = TeamMessage.find(params[:id])
    @header_text = 'Edit Message'
    @team_message.attributes = params[:team_message]
    if @team_message.save
      redirect_to team_messages_path, notice: 'Message was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /team_messages/1
  def destroy
    @team_message = TeamMessage.find(params[:id])
    @team_message.destroy
    redirect_to team_messages_path, notice: 'Message was successfully deleted'
  end

  # GET /team_messages/:id/download
  def download
    @team_message = TeamMessage.find(params[:id])
    filepath = File.join(UPLOAD_PATH, @team_message.file)
    basename = File.basename filepath
    basename = basename[basename.index('.')+1..-1]
    raise "Invalid Download: #{basename}/#{params[:filename]}" unless File.exists? filepath and File.file? filepath
    send_file filepath, filename: basename
  end

  private
  def _send message_params
    @team_message = TeamMessage.new(message_params)

    unless current_user.is_admin
      @team_message.team_id = current_user.team_id
      @team_message.from_admin = false
    else
      @team_message.from_admin = true
    end

    raise unless @team_message.save
  end
end

app/views/team_messages/_form.html.haml
= form_for @team_message do |f|
  %fieldset.no-border
    - if current_user_admin?
      = render partial: 'layouts/form_row', locals: {f: f, model: @team_message, html_form: f.select(:team_id, Team.options_list.select{|t| not t[1].blank?}), row_id: :team_id, row_name: 'Team', small_size: 12, large_size: 6, hint: 'Team(s) to send message to', required: true}
    = render partial: 'layouts/form_row', locals: {f: f, model: @team_message, html_form: f.file_field(:file_upload), row_id: :file_upload, row_name: 'Upload File', small_size: 12, large_size: 6, hint: 'Optional. Upload a file along with your submission', required: false}
    = render partial: 'layouts/form_row', locals: {f: f, model: @team_message, html_form: f.text_field(:subject), row_id: :subject, row_name: 'Subject', small_size: 12, large_size: 12, hint: 'Subject of the message', required: true}
    = render partial: 'layouts/form_row', locals: {f: f, model: @team_message, html_form: f.text_area(:content, style: 'height: 100px;'), row_id: :content, row_name: 'Content', small_size: 12, large_size: 12, hint: 'Content of the message', required: true}
    .small-3.columns.left
      = f.submit ((%w{new create}.include? params[:action]) ? 'Send' : 'Edit'), class: 'button'

app/views/team_messages/_message.html.haml
%tr{class: (team_message.created_at > @last_time_checked ? 'new' : '')}
  %td.has-inline-list
    %ul.inline-list
      %li
        = link_to fa_icon(:reply), team_messages_reply_path(team_message.id)
      - if current_user_admin?
        %li= link_to fa_icon('trash-o'), team_message, method: :delete, data: { confirm: 'Are you sure?' }
  - if current_user_admin?
    %td= "Team #{team_message.team.name}"
  %td
    = link_to team_message.subject, team_message
    - if team_message.file?
      &nbsp;
      &nbsp;
      = fa_icon :download
  %td
    = team_message.created_at.strftime '%I:%M:%S %p'

app/views/team_messages/_table.html.haml
%table.small-12.columns.messages
  %thead
    %tr
      - if current_user_admin?
        %th.small-1.columns
        %th.small-2.columns Team
        %th.small-6.columns Subject
        %th.small-3.columns Sent
      - else
        %th.small-1.columns
        %th.small-8.columns Subject
        %th.small-4.columns Sent

  %tbody
    - messages.each do |team_message|
      = render partial: 'message', locals: {team_message: team_message}
%br

app/views/team_messages/edit.html.haml
= render 'form'

app/views/team_messages/index.html.haml
.row
  .small-5.columns.small-offset-7
    = form_tag team_messages_path, method: :get, class: 'foundation' do
      .row.collapse
        .small-2.columns
          - if params[:search].blank?
            &nbsp;
          - else
            = link_to 'Clear', team_messages_path, class: 'button prefix'
        .small-10.columns
          = text_field_tag 'search', params[:search], placeholder: 'search'

.row
  %dl.messages.vertical.tabs{'data-tab'=>''}
    %dd.active= link_to 'Inbox', '#inboxTab'
    %dd= link_to 'Outbox', '#outboxTab'
    %br
    = link_to 'New Message', new_team_message_path, class: 'button'
    %br
    %small
      Refresh in
      %span#refresh-timer(data-refresh-page="yes")
      sec

  .tabs-content.vertical
    #inboxTab.content.active
      = render partial: 'table', locals: {messages: @inbox}
    #outboxTab.content
      = render partial: 'table', locals: {messages: @outbox}

app/views/team_messages/show.html.haml
.row
  .twelve.columns.panel
    %h3= @team_message.subject
    %b
      = "Team #{@team_message.team.name}"
      %br
      %br
      Sent
      = @team_message.created_at.strftime '%I:%M:%S %p'
      - unless @file_name.nil?
        %br
        %br
        = link_to fa_icon(:download, text: @file_name), team_message_download_path(@team_message.id)
    %br
    %br
    %blockquote.message_content
      = simple_format @team_message.content
  .left
    = link_to fa_icon(:reply, text: 'Reply'), team_messages_reply_path(@team_message.id), class: 'button'