config/routes.rb
ScoreEngine::Application.routes.draw do
  # Root
  root :to => 'page#home'

  # Users
  devise_for :users

  # Teams
  resources :teams
  get '/teams/:id/graph' => 'teams#graph', as: :team_graph

  # Client Updates
  get '/client_update/poll' => 'client_update#poll'

  # Services
  post '/services/:id/clear' => 'services#clear', as: :clear_service
  post '/logs/:id/clear/:log_id' => 'services#clear', as: :clear_service_log
  get '/services/:id/status/:last_log_id' => 'services#status'
  post '/services/:id/power' => 'services#power', as: :service_power
  get '/services/:id/graph/:type' => 'services#graph', as: :services_graph
  resources :services

  # Scoreboard
  get '/scoreboard' => 'scoreboard#index', as: :scoreboard
  get '/scoreboard/graph/:graph_model/:id/:graph_name' => 'scoreboard#graph'

  # Users
  get '/users' => 'users#index', as: :users
  get '/users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update', as: :user

  # Team Messages
  resources :team_messages, path: 'messages'
  get '/messages/new/:reply_id' => 'team_messages#new', as: :team_messages_reply
  get '/messages/:id/download' => 'team_messages#download', as: :team_message_download

  # Server Manager
  get '/serverManager' => 'server_manager#index', as: :server_manager
  post '/serverManager/refresh' => 'server_manager#refresh', as: :server_manager_refresh
  post '/serverManager/start_libvirt' => 'server_manager#start_libvirt', as: :server_manager_start_libvirt
  get '/serverManager/:id/:command' => 'server_manager#command', as: :server_manager_command
  post '/serverManager/:id/:command' => 'server_manager#command'

  # Tools
  get 'tools/hash' => 'tools#hash', as: :hash_tool
  post 'tools/hash' => 'tools#hash_post'
  get 'tools/dns' => 'tools#dns', as: :dns_tool
  post 'tools/dns' => 'tools#dns_post'
  get 'tools/daemon_log' => 'tools#daemon_log', as: :daemon_log
end

app/views/layouts/_form_row.html.haml
- has_error = ((not f.nil?) and (not model.nil?) and (model.errors.has_key? row_id) and (model.errors[row_id].length > 0))
.columns.left.hint{class: "small-#{small_size} #{large_size.nil? ? '' : "large-#{large_size}"} #{has_error ? 'error' : ''}"}
  - if f.nil?
    = label_tag do
      = row_name
      - if required
        %em.formee-req *
  - else
    = f.label row_id do
      = row_name
      - if required
        %em.formee-req *
  = html_form
  %small.hint= hint
  %small.error= model.errors[row_id].first if has_error

app/views/layouts/_form_row_slider.html.haml
.small-6.large-3.columns.left
  %label= row_name
  .toggle
    = f.check_box row_id
    = f.label row_id do
      %span.slider

app/views/layouts/_header.html.haml
.contain-to-grid
  .top-bar{'data-topbar'=>''}
    %ul.title-area
      %li.name{class: (daemon_running? ? 'running' : 'not-running')}
        %h1= link_to fa_icon(:cogs, text: '&nbsp;Score&nbsp;Engine'.html_safe), '/'
      %li.toggle-topbar.menu-icon
        = link_to '<span>Menu</span>'.html_safe, '#'

    %section.top-bar-section
      %ul.right
        - if user_signed_in?
          - unless current_user.is_red_team
            %li#messages_link{class: (TeamMessage.user_new_messages(current_user, last_time_inbox_checked) > 0 ? 'new_messages' : '')}
              = link_to fa_icon(:envelope, text: 'Messages'), team_messages_path
          %li
            = link_to fa_icon(:dashboard, text: 'Services'), services_path
          - if current_user.is_admin
            %li
              = link_to fa_icon(:desktop, text: 'Servers'), server_manager_path
          %li.has-dropdown
            = link_to fa_icon(:stethoscope, text: 'Tools'), '#'
            %ul.dropdown
              %li= link_to fa_icon(:lock, text: 'Hash'), hash_tool_path
              %li= link_to fa_icon('info-circle', text: 'DNS'), dns_tool_path
              - if current_user.is_admin
                %li= link_to fa_icon(:group, text: 'Users'), users_path
                %li= link_to fa_icon('list-ul', text: 'Daemon Log'), daemon_log_path
          %li.has-button
            = link_to fa_icon(:user, style: 'color:black', text: 'Logout'), destroy_user_session_path, method: :delete, class: 'small button'

#global_alert
  .row
    .small-8.columns.small-offset-2.alert-box{style:'visibility:'+(flash[:error] || flash[:alert] || flash[:notice] ? 'visible' : 'hidden'), class:(flash[:error] || flash[:alert] ? 'alert' : '')}
      = flash[:error]
      = flash[:alert]
      = flash[:notice] unless flash[:error] or flash[:alert]

- if not @header_text.nil?
  %header#titlebar{class: @header_class}
    .row
      .small-12.columns
        %h1.text
          - unless @header_icon.blank?
            = fa_icon @header_icon
          = @header_text

app/views/layouts/_sidebar.html.haml
%ul.nav-bar.vertical
  %li
    = link_to 'Nav 1', '#'
  %li
    = link_to 'Nav 2', '#'

app/views/layouts/application.html.haml
!!!html
:plain
  <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
  <!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
  <!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
  <!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
  <!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->

%head
  %meta{charset: 'utf-8'}

  / Uncomment to make IE8 render like IE7
  / <meta http-equiv="X-UA-Compatible" content="IE=7" />

  / Set the viewport width to device width for mobile
  %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}

  %title= content_for?(:title) ? yield(:title) : "Score Engine - #{@header_text}"

  :javascript
    var controllerName = '#{params[:controller]}';
    var actionName = '#{params[:action]}';
    var is_logged_in = #{current_user != nil ? 'true' : 'false'};
    var is_admin = #{current_user != nil && current_user.is_admin ? 'true' : 'false'};
    var is_red_team = #{current_user != nil && current_user.is_red_team ? 'true' : 'false'};
    var status_class = { #{ServiceLog::STATUS.keys.map{|s| "'#{s}': '#{status_class(s)}'"}.join(', ')} };
    var status_img = { #{ServiceLog::STATUS.keys.map{|s| "'#{s}': '#{status_img(s)}'"}.join(', ')} };

  = javascript_include_tag :application
  = javascript_include_tag :modernizr
  = stylesheet_link_tag :application

  = csrf_meta_tags

%body
  -# There is a bug in foundation v5.0.2 which required JS include in body
  -# This will be fixed in foundation v5.0.3
  -# javascript_include_tag :foundation

  = render 'layouts/header'

  .row.content
    .twelve.columns
      = yield

:plain
  </html>

app/views/layouts/application_v2.html.haml
!!!html
:plain
  <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
  <!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
  <!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
  <!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
  <!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
%html
  %head
    %meta{charset: 'utf-8'}
    %title= content_for?(:title) ? yield(:title) : 'Score Engine'
    :javascript
      var controllerName = '#{params[:controller]}';
      var actionName = '#{params[:action]}';
      var status_classes = {'-1': 'off', '0':'running', '1':'down', '2':'access', '3':'error'};
      var status_names = #{ServiceLog::STATUS.to_json};
    = stylesheet_link_tag :application_v2
    = csrf_meta_tags
    
  %body.skin-blue
    %header.header
      = link_to 'ScoreEngine v2', '/', class: 'logo'

      %nav.navbar.navbar-static-top(role="navigation")
        %a.navbar-btn.sidebar-toggle(href="#" data-toggle="offcanvas" role="button")
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-right
          %ul.nav.navbar-nav
            %li.dropdown.messages-menu
              %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
                = fa_icon(:envelope)
                %span.label.label-success 1
              %ul.dropdown-menu
                %li.header You have 1 message
                %li
                  %ul.menu
                    %li
                      %a(href="#")
                        .pull-left
                          = image_tag 'blue.png', class: 'img-circle'
                        %h4
                          Team Alpha
                          %small
                            = fa_icon('clock-o')
                            5 mins
                        %p RE: Inject #1
                %li.footer
                  = link_to 'View all messages', '#'
            %li.dropdown.notifications-menu
              %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
                = fa_icon(:warning)
                %span.label.label-warning 10
              %ul.dropdown-menu
                %li.header You have 10 notifications
                %li
                  %ul.menu
                    %li
                      %a(href='#')
                        %i.warning.fa.fa-file
                        5 injects to be graded
                %li.footer
                  = link_to 'View all notifications', '#'
            -# %li.dropdown.tasks-menu
              %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
                = fa_icon(:tasks)
                %span.label.label-danger 9
              %ul.dropdown-menu
                %li.header You have 9 tasks
                %li
                  %ul.menu
                    %li
                      %a(href='#')
                        %h3
                          CPU
                          %small.pull-right 20%
                        .progress.xs
                          .progress-bar.progress-bar-aqua(style="width:20%" rolw="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100")
                            %span.sr-only 20% Complete
                %li.footer
                  = link_to 'View all tasks', '#'
            %li.dropdown.user.user-menu
              %a(href='#' class='dropdown-toggle' data-toggle='dropdown')
                %i.ion-android-contact
                %span
                  = current_user.username
                  %i.caret
              %ul.dropdown-menu
                %li.user-header.bg-light-blue
                  = image_tag "#{current_user.color}.png", class:'img-circle', alt:'User Image'
                  %p
                    = "#{current_user.username} - #{current_user.color.capitalize} Team"
                    %small
                      - if current_user.team_id
                        = current_user.team.name
                      - else
                        Global User
                %li.user-body
                  .col-xs-4.text-center
                    = link_to 'Services', "#{services_path}#team#{current_user.team_id}Tab"
                  .col-xs-4.text-center
                    = link_to 'Messages', "#{team_messages_path}#inboxTab"
                  .col-xs-4.text-center
                    = link_to 'Tools', '#'
                %li.user-footer
                  .pull-left
                    = link_to 'Profile', edit_user_path(current_user), class: 'btn btn-default btn-flat'
                  .pull-right
                    = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat'
    .wrapper.row-offcanvas.row-offcanvas-left
      %aside.left-side.sidebar-offcanvas
        %section.sidebar
          .user-panel
            .pull-left.image
              = image_tag "#{current_user.color}.png", class: 'img-circle', alt: 'User Image'
            .pull-left.info
              %p= "Hello, #{current_user.username}"
              = link_to fa_icon('circle', class:'text-success', text: 'Online'), '#"'
          %form.sidebar-form(action='#' method='get')
            .input-group
              %input.form-control(type='text' name='q' placeholder='Search...')
              %span.input-group-btn
                %button.btn.btn-flat#search-btn(type='submit' name='search')
                  = fa_icon(:search)
          %ul.sidebar-menu
            %li.active
              = link_to fa_icon(:dashboard, text: 'Dashboard'), '#'
            %li.treeview.active
              %a(href='#')
                = fa_icon(:cloud)
                %span Services
                = fa_icon('angle-left', class: 'pull-right')
              %ul#serviceMenu.treeview-menu(style="display:block")
      %aside.right-side
        %section.content-header
          %h1
            Dashboard
            / %small Control Panel
          %ol.breadcrumb
            %li= link_to fa_icon(:dashboard, text: 'Home'), '#'
            %li.active Dashboard
        %section.content
          .row
            = yield

  = javascript_include_tag :application_v2
  = javascript_include_tag :modernizr